eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
