spring:
  redis:
    host: 47.93.37.94
    port: 6379
#    password: 123456

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
